# Generated by Django 4.1.4 on 2023-01-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Course', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
    ]
