# Generated by Django 4.1.4 on 2023-01-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.CharField(max_length=200)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Name', models.CharField(max_length=20)),
                ('CompanyName', models.CharField(max_length=30)),
            ],
        ),
    ]
