# Generated by Django 4.1.4 on 2023-01-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OGP', models.IntegerField()),
                ('CP', models.IntegerField()),
                ('SL', models.IntegerField()),
                ('HC', models.IntegerField()),
            ],
        ),
    ]
