# Generated by Django 4.1.4 on 2023-01-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_projectsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsummary',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
