# Generated by Django 4.1.4 on 2023-01-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=16)),
                ('Email', models.EmailField(max_length=254)),
                ('ContactNumber', models.IntegerField()),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Qualification', models.CharField(max_length=20)),
                ('InstituteName', models.CharField(max_length=20)),
                ('YearOfPassing', models.IntegerField()),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSigup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=16)),
                ('Designation', models.CharField(max_length=16)),
                ('CompanyName', models.CharField(max_length=20)),
                ('ContactEmail', models.EmailField(max_length=254)),
                ('ContactNumber', models.IntegerField()),
                ('ServiceType', models.CharField(max_length=15)),
                ('ServiceDetails', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
    ]
